// This file is auto-generated by @hey-api/openapi-ts

export type ActionInputModel = {
    documentTypeId: string;
    actionName?: string | null;
};

export type BlockActionInputModel = {
    documentTypeId: string;
    actionName?: string | null;
};

export type CheckInput = {
    documentTypeId: string;
};

export type CheckResult = {
    isOk: boolean;
    message?: string | null;
    actionUrl?: string | null;
    actionName?: string | null;
    actionButtonText?: string | null;
};

export type ConfigModel = {
    isDeliveryApiInstalled: boolean;
    isDeliveryApiEnabled: boolean;
    codebaseSrcPath?: string | null;
    templatesRootFolderPath?: string | null;
    readonly isNextJsInstalled?: boolean | null;
    isReactTestingInstalled?: boolean | null;
    isXpediteTypescriptCodeInstalled?: boolean | null;
    isEnvFileInstalled?: boolean | null;
    isContentInPlace: boolean;
    readonly isComplete: boolean;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type GenerateApiModel = {
    componentName?: string | null;
    variantName?: string | null;
    documentTypeId: string;
    selectedProperties: Array<(string)>;
};

export type GenerateBlockApiModel = {
    componentName?: string | null;
    variantName?: string | null;
    documentTypeId: string;
    selectedProperties: Array<(string)>;
    settingsTypeId?: string | null;
    selectedSettings?: Array<(string)> | null;
};

export type GeneratedFile = {
    relativeFilePath: string;
    contents: string;
    isAIGenerated: boolean;
    readonly folderPath?: string | null;
    readonly fileName?: string | null;
    readonly extension: string;
};

export type GeneratedFiles = {
    groupName?: string | null;
    files: Array<(GeneratedFile)>;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PostApiV1XpediteAddEnvFileResponse = string;

export type PostApiV1XpediteAssistantBlockActionData = {
    requestBody?: BlockActionInputModel;
};

export type PostApiV1XpediteAssistantBlockActionResponse = Array<(CheckResult)>;

export type PostApiV1XpediteAssistantBlockChecksData = {
    requestBody?: CheckInput;
};

export type PostApiV1XpediteAssistantBlockChecksResponse = Array<(CheckResult)>;

export type PostApiV1XpediteAssistantTemplateActionData = {
    requestBody?: ActionInputModel;
};

export type PostApiV1XpediteAssistantTemplateActionResponse = Array<(CheckResult)>;

export type PostApiV1XpediteAssistantTemplateChecksData = {
    requestBody?: CheckInput;
};

export type PostApiV1XpediteAssistantTemplateChecksResponse = Array<(CheckResult)>;

export type PostApiV1XpediteGenerateBlockData = {
    requestBody?: GenerateBlockApiModel;
};

export type PostApiV1XpediteGenerateBlockResponse = GeneratedFiles;

export type PostApiV1XpediteGeneratePartialData = {
    requestBody?: GenerateApiModel;
};

export type PostApiV1XpediteGeneratePartialResponse = GeneratedFiles;

export type PostApiV1XpediteGenerateTemplateData = {
    requestBody?: GenerateApiModel;
};

export type PostApiV1XpediteGenerateTemplateResponse = GeneratedFiles;

export type GetApiV1XpediteGetConfigResponse = ConfigModel;

export type PostApiV1XpediteSaveBlockData = {
    force?: boolean;
    requestBody?: GenerateBlockApiModel;
};

export type PostApiV1XpediteSaveBlockResponse = string;

export type PostApiV1XpediteSavePartialData = {
    force?: boolean;
    requestBody?: GenerateApiModel;
};

export type PostApiV1XpediteSavePartialResponse = string;

export type PostApiV1XpediteSaveTemplateData = {
    force?: boolean;
    requestBody?: GenerateApiModel;
};

export type PostApiV1XpediteSaveTemplateResponse = string;